version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      #- $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - $(aws ecr get-login --no-include-email --region eu-west-1)
      #- REPOSITORY="202993557868.dkr.ecr.eu-west-1.amazonaws.com/node-app
      #- COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      #- IMAGE_TAG=$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t node-app .
      #- docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - docker tag node-app:latest 202993557868.dkr.ecr.eu-west-1.amazonaws.com/node-app:latest
      #- docker tag $IMAGE_NAME:$IMAGE_TAG $REPOSITORY
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 202993557868.dkr.ecr.eu-west-1.amazonaws.com/node-app:latest
      #- docker push $REPOSITORY_URI:latest
      #- docker push $REPOSITORY
      - echo Writing image definitions file...
      #- printf '[{"name":"$IMAGE_NAME","imageUri":"%s"}]' $REPOSITORY > imagedefinitions.json
      #- cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
